- apps/gasi/package.json
- apps/gasi/src/index.ts
- apps/gasi/tsconfig.json
- pnpm-lock.yaml
trpc 서버를 elysia에서 fastify로 재설정하였습니다. 
client에서 bun을 사용해서 모노레포 환경을 구축하는 것이 해커톤 기간 상 큰 부담이 되어 pnpm으로 변환하게 되면서, CI를 함께 태울 때 효과적인 파이프라인과 최적화를 위해 pnpm과 fastify로 migrate하게 됐습니다. 
- bun 관련 프로세스 삭제
- pnpm으로 migrate
- fastify로 migrate
ts-node랑 nodemon으로 hot-reload를 설정하는 것보다 tsx를 사용하는 것이 나을 것 같아서 tsx로 설정해두었습니다. 
[tsx 문서]
- https://www.npmjs.com/package/tsx
> feat(gasi): trpc 서버 fasity로 migration

- package.json
- pnpm-lock.yaml
> chore(workspace): update pnpm to `9.14.2`

- apps/gasi/package.json
- apps/gasi/prisma/schema.prisma
- pnpm-lock.yaml
데이터베이스 접근용 prisma와 인증용  jsonwebtoken을 설치했습니다.
> chore(gasi): `jsonwebtoken`과 `prisma` 설치

- apps/client/package.json
- apps/client/src/app/api/sentry-example-api/route.ts
- apps/client/src/app/global-error.tsx
- apps/client/src/app/sentry-example-page/page.tsx
- apps/client/src/features/home/ui/popular-assignment.tsx
- apps/client/src/pages/_error.jsx
- apps/client/src/shared/api/client.ts
- apps/client/src/shared/lib/utils.ts
- apps/client/src/shared/ui/carousel.tsx
- pnpm-lock.yaml
linter에 잡히는 오류 해결
PR 시 작동하는 lint workflow 실패를 수정했습니다.
> fix(workspace): lint에 잡히는 부분 해결

- apps/gasi/src/mockUtils.ts
- apps/gasi/src/router.ts
- apps/gasi/src/routes/asgmt.ts
- apps/gasi/src/routes/auth.ts
- apps/gasi/src/routes/submission.ts
- apps/gasi/src/routes/user.ts
- packages/specs/src/context.ts
- packages/specs/src/index.ts
- packages/specs/src/trpc.ts
요청 스키마에서 일반 string을 받아 명확성이 떨어지고 trpc-ui에서 오류가 발생합니다. `object`로 감싸 문제를 해결합니다.
> refactor(gasi): 일반 `string`을 받지 않도록 수정

- apps/client/package.json
- apps/client/src/shared/lib/trpc.ts
- packages/specs/package.json
- packages/specs/src/index.ts
- pnpm-lock.yaml
클라이언트에서 `createCallerFactory`, `createCaller`를 사용하여 타입 정의 오류로 인해 Docker ci가 깨지는 현상 발생
-> `@request/specs`에서 `createCaller`  함수를 노출하여 클라이언트에서 호출하여 mock API를 사용하기
+ `@request/specs`가 devDependencies로 정의되어 있었으나  zod schema 등의 사용이 필요함을 고려하면 dependencies로 이동함이 적절, Docker 빌드 과정에서 최적화를 위해 실행에 필요 없는 dependencies(예: devDependencies)는 자동으로 제외함으로 의존성 설정에 유의해주세요!!
> fix(specs): createCaller를 노출하여 빌드 오류 수정

- apps/gasi/src/index.ts
- apps/gasi/src/model/schema.ts
Submission: assignmentId의 unique 제거
User: submissions를 ref로 변경
> fix(gasi): 올바르지 않은 스키마 수정 

- codedeploy/docker-compose.yml
> ci(workspace): nginx 컨테이너가 업데이트 시 마다 재시작되도록 설정

- apps/gasi/src/context.ts
- apps/gasi/src/routes/auth.ts
사용자 온보딩 시 필요한 `v1.auth.register` 엔드포인트를 구현했습니다. `v1.auth.kakao` 응답에 registered: false 일 경우 이 엔드포인트에 요청을 보내 온보딩을 진행합니다.
참고: 요청 스키마 및 설명
```ts
export const RegisterUserRequestSchema = z.object({
// 사용자 이름
name: z.string(),
// GitHub 이메일
email: z.string().email(),
// 희망직무, 기술, 기업
prompt: AssignmentPromptSchema,
// 학력은 빼먹었습니다... 알잘딱해주세용~
});
```
> feat: `v1.auth.register` 엔드포인트 구현

- apps/client/src/app/callback/page.tsx
- apps/client/src/features/callback/types/global.d.ts
- apps/client/src/features/onboarding/ui/auth.tsx
- apps/client/src/pages/callback/callback-page.tsx
- apps/client/src/pages/onboarding-page.tsx
- apps/client/src/shared/lib/cookie.ts
- apps/client/src/widgets/script-provider.tsx
- apps/client/src/widgets/ui/kakao-script.tsx
- apps/client/tailwind.config.ts
> feat(client): 카카오 로그인 API 연동

- apps/gasi/src/auth/token.ts
- apps/gasi/src/model/schema.ts
- apps/gasi/src/routes/user.ts
> feat(gasi): v1.user.me 엔드포인트

- apps/gasi/src/model/schema.ts
- apps/gasi/src/routes/asgmt.ts
- packages/specs/src/schema/assignment.ts
`v1.asgmt.list`, `v1.asgmt.get`, `v1.asgmt.generate` 함수를 구현합니다.
> feat(gasi): `v1.asgmt` 엔드포인트들 구현

- apps/client/package.json
- apps/client/src/pages/callback/callback-page.tsx
- apps/client/src/shared/api/trpc.ts
- apps/client/src/widgets/query-provider.tsx
- pnpm-lock.yaml
trpc로 인한 빌드 안되는 오류 해결했습니다.
withTRPC로 감싸지 않은 컴포넌트가 빌드되지 않는 오류를 해결하기 위해 진행하게 되었습니다.
클라이언트 컴포넌트는 컴포넌트 형식을 아래와 같이 따라야 합니다.
```typescript
const SomeComponent = () => {
...
}
export default trpc.withTRPC(SomeComponent)
```
> fix(client): trpc로 인한 빌드 안되는 오류 해결

- apps/gasi/src/model/schema.ts
- apps/gasi/src/routes/submission.ts
- packages/specs/src/index.ts
- packages/specs/src/schema/review.ts
- packages/specs/src/schema/submission.ts
- packages/specs/src/schema/user.ts
> [!IMPORTANT]
> 확인하셨으면 리뷰해 주시고, FE 두 분 다 리뷰되었으면 마지막 리뷰하신 분이 머지해주세요.
`v1.submission` 아래의 엔드포인트를 `v1.submission.file`, `v1.submission.files`를 제외하고 구현했습니다.
구현된 엔드포인트
- `v1.submission.init`
- `v1.submission.cancel`
- `v1.submission.review`
- `v1.submission.reviewEntries`
몇 가지 빠진 데이터가 있어 추가하였고, User의 데이터 형태가 변경되었습니다.
**UserSchema**
```diff
export const UserSchema = z.object({
id: z.string(),
name: z.string().optional(),
email: z.string().email().optional(),
registered: z.boolean().default(false),
providers: z.object({
kakao: z
.object({
uid: z.string(),
connectedAt: z.string().datetime(),
})
.optional(),
}),
lastGeneratedAssignment: z.string().optional(),
- submissions: z.array(SubmissionSchema),
+ submissions: z.array(z.string()),
prompt: AssignmentPromptSchema.optional(),
});
``` …
> feat(gasi): `v1.submission` 엔드포인트 구현

- apps/client/next.config.mjs
- apps/gasi/src/docker.ts
- apps/gasi/src/index.ts
- apps/gasi/src/routes/submission.ts
> lint(workspace): apply formatting

- apps/gasi/src/model/schema.ts
> fix(gasi): remove unique assignmentId

- apps/gasi/src/docker.ts
- apps/gasi/src/router.ts
- apps/gasi/src/routes/submission.ts
- packages/specs/src/index.ts
- packages/specs/src/schema/user.ts
> feat(gasi): `v1.submission.list`

- apps/gasi/src/routes/submission.ts
> fix(gasi): `v1.submission.list`

- apps/gasi/src/routes/submission.ts
> fix(gasi): `v1.submission.list` user.id

- .github/workflows/publish-dev.yml
- apps/gasi/src/docker.ts
- apps/gasi/src/index.ts
> fix(gasi): github 레포지토리 생성

- apps/gasi/src/model/schema.ts
- apps/gasi/src/routes/submission.ts
- packages/specs/src/index.ts
- packages/specs/src/schema/review.ts
> feat(gasi)!: adopt new review schema

- apps/gasi/src/ari.ts
- apps/gasi/src/index.ts
> feat(gasi): ari 리뷰 요청

- apps/client/src/app/test/page.tsx
- apps/client/src/entities/assignment/ui/card/assignment-card.tsx
- apps/client/src/entities/assignment/ui/card/assignment-list.tsx
- apps/client/src/entities/onboarding/schema/onboard-funnel.ts
- apps/client/src/features/assignment/create/components/funnels/confirm-userInfo.tsx
- apps/client/src/features/assignment/create/components/funnels/create-success.tsx
- apps/client/src/features/home/ui/home-banner.tsx
- apps/client/src/features/home/ui/popular-assignment/components/carousel-indicator.tsx
- apps/client/src/features/home/ui/popular-assignment/components/popular-card.tsx
- apps/client/src/features/home/ui/popular-assignment/popular-assignment.tsx
- apps/client/src/features/onboarding/profile/components/funnels/components/onboarding-success.tsx
- apps/client/src/features/onboarding/profile/components/funnels/input-field.tsx
- apps/client/src/features/onboarding/profile/components/funnels/input-github.tsx
- apps/client/src/features/onboarding/profile/components/funnels/input-name.tsx
- apps/client/src/features/onboarding/profile/components/funnels/input-tech-and-company.tsx
- apps/client/src/features/onboarding/profile/components/funnels/onboarding-layout.tsx
- apps/client/src/features/onboarding/ui/onboarding-carousel.tsx
- apps/client/src/shared/ui/button.tsx
- apps/client/src/shared/ui/card.tsx
- apps/client/src/shared/ui/command.tsx
- apps/client/src/shared/ui/menubar.tsx
- apps/client/src/widgets/layout/footer/footer.tsx
- apps/client/src/widgets/layout/header/default-header.tsx
- apps/client/src/widgets/layout/header/header.tsx
- apps/client/src/widgets/layout/header/notification-icon.tsx
과제 생성 플로우 레이아웃을 수정하고, 성공 페이지 API를 연결했습니다.
> feat(client): 신규 과제 생성 성공 페이지 및 UI 개선

- apps/gasi/src/agi.ts
- apps/gasi/src/routes/asgmt.ts
> feat(gasi): request asgmt generation to agi

- apps/gasi/src/agi.ts
- apps/gasi/src/ari.ts
- apps/gasi/src/index.ts
> fix(gasi): instant submit

- apps/client/package.json
- apps/client/src/app/test/page.tsx
- apps/client/src/entities/assignment/create/schema/create-assignment-schema.ts
- apps/client/src/features/assignment/create/components/funnels/create-success.tsx
- apps/client/src/features/assignment/create/components/funnels/creating-assignment.tsx
- apps/client/src/features/assignment/create/components/funnels/input-userinfo.tsx
- apps/client/src/features/assignment/ui/assignment-banner.tsx
- apps/client/src/features/evaluation/ui/ongoing-assignment.tsx
- apps/client/src/pages/assignment-detail-page.tsx
- apps/client/src/pages/assignment/business-assignment-page.tsx
- apps/client/src/pages/evaluation/evaluation-page.tsx
- apps/client/src/shared/lib/cookie.ts
- apps/client/src/widgets/layout/header/header.tsx
- apps/client/src/widgets/ui/banner.tsx
- apps/client/src/widgets/ui/category-filter/category-filter.tsx
> feat(client): 쿠키 삭제 기능 추가 및 UI 텍스트 개선

- apps/gasi/src/routes/submission.ts
> fix(gasi): submission이 preparing started일때만 생성 불가

- apps/client/src/features/evaluation/ui/evaluation-item.tsx
- apps/client/src/pages/assignment-detail-page.tsx
- apps/client/src/pages/evaluation/evaluation-page.tsx
- apps/client/src/widgets/layout/header/default-header.tsx
> refactor(client): defualt image, 헤더 로그인 상태 로직 수정

- apps/client/src/features/evaluation/ui/evaluation-result-info.tsx
- apps/client/src/pages/markdown.tsx
> feat(client): 동적 ID를 사용하여 평가 결과 정보 쿼리 수정 및 마크다운 페이지 코드 정리

- apps/gasi/src/routes/submission.ts
> fix(gasi): remove owner check

- apps/gasi/src/agi.ts
> fix(gasi): don't panic if agi req failed

- apps/gasi/src/routes/asgmt.ts
> fix(gasi): asgmt db apply
